export const bachataMoves: string[] = [
	'accent',
	'aerial',
	'angel step',
	'arm styling',
	'arm wave',
	'arm wrap',
	'assisted jump',
	'assisted lean',
	'back dip',
	'basic step',
	'body roll',
	'body wave',
	'break',
	'cambre',
	'check turn',
	'chest isolation',
	'chest to chest',
	'circular walk',
	'close connection',
	'closed position',
	'contact improvisation',
	'copa',
	'cross body lead',
	'cuddle',
	'cuddle block',
	'cuddle walkover',
	'death drop',
	'delayed turn',
	'derecho',
	'dip',
	'double prep right turn',
	'double time',
	'double turn',
	'drag step',
	'drive',
	'enchufla',
	'entrance',
	'exit',
	'finger trails',
	'five step swing',
	'flow',
	'forward and back',
	'free spin',
	'hair flick',
	'hammer',
	'hammerlock',
	'hand flick',
	'hand styling',
	'hand toss',
	'head roll',
	'head slide',
	'heel turn',
	'hip circle',
	'hip isolation',
	'hip roll',
	'inside turn',
	'isolation',
	'kick',
	'lead under arm',
	'lean',
	'lean back',
	'left turn',
	'lift',
	'madrid',
	'majao',
	'neck wrap',
	'no hands',
	'one hand connection',
	'open connection',
	'open position',
	'outside turn',
	'overcoat',
	'pass partner',
	'pause',
	'pivot turn',
	'press and walk',
	'pretzel',
	'push and pull',
	'recovery',
	'reverse cross body',
	'rib cage roll',
	'right turn',
	'rotation clockwise',
	'send out',
	'separate cuddle',
	'shadow position',
	'shoulder isolation',
	'shoulder lead',
	'side basic',
	'side dip',
	'slide',
	'sliding doors',
	'slow motion',
	'snake',
	'spiral turn',
	'stomp',
	'sweetheart',
	'sweetheart block',
	'sweetheart half turn',
	'swing out',
	'swivels',
	'syncopation',
	'tap step',
	'toe tap',
	'transition',
	'triple step',
	'trust fall',
	'walkover',
	'wrap and unwrap',
	'y dip',
];

export const salsaMoves: string[] = [
	'accent',
	'aerial',
	'arm styling',
	'back spot turn',
	'basic step',
	'break',
	'check turn',
	'closed position',
	'copa',
	'cross body lead',
	'cuban motion',
	'cuban shuffle',
	'dile que no',
	'dip',
	'double turn',
	'enchufla',
	'entrance',
	'exit',
	'exhibela',
	'flare',
	'flow',
	'footwork',
	'free spin',
	'guapea',
	'hair comb',
	'hammerlock',
	'hand styling',
	'hand toss',
	'hook turn',
	'inside turn',
	'isolation',
	'kick',
	'left turn',
	'lift',
	'mambo step',
	'open break',
	'open position',
	'outside turn',
	'pa arriba',
	'paseo',
	'pivot turn',
	'right turn',
	'rueda de casino',
	'setenta',
	'shadow position',
	'shines',
	'shoulder check',
	'side step',
	'slide',
	'sombrero',
	'stomp',
	'suzie q',
	'sweetheart',
	'syncopation',
	'tap step',
	'transition',
	'triple turn',
	'vacilala',
	'wrap and unwrap',
];

export function getMovesForDance(dance: string): string[] {
	switch (dance) {
		case 'bachata': return bachataMoves;
		case 'salsa': return salsaMoves;
		default: return [...new Set([...bachataMoves, ...salsaMoves])].sort();
	}
}
