export const bachataMoves: string[] = [
	'accent',
	'aerial',
	'arm styling',
	'arm wave',
	'arm wrap',
	'assisted jump',
	'assisted lean',
	'back dip',
	'basic step',
	'body roll',
	'body wave',
	'break',
	'cambre',
	'check turn',
	'chest isolation',
	'chest to chest',
	'close connection',
	'closed position',
	'contact improvisation',
	'copa',
	'cross body lead',
	'cuddle',
	'death drop',
	'derecho',
	'dip',
	'double time',
	'double turn',
	'drag step',
	'enchufla',
	'entrance',
	'exit',
	'finger trails',
	'flow',
	'forward and back',
	'free spin',
	'hair flick',
	'hammerlock',
	'hand flick',
	'hand styling',
	'hand toss',
	'head roll',
	'head slide',
	'heel turn',
	'hip circle',
	'hip isolation',
	'hip roll',
	'inside turn',
	'isolation',
	'kick',
	'lean',
	'lean back',
	'left turn',
	'lift',
	'majao',
	'neck wrap',
	'no hands',
	'one hand connection',
	'open connection',
	'open position',
	'outside turn',
	'pause',
	'pivot turn',
	'pretzel',
	'push and pull',
	'recovery',
	'reverse cross body',
	'rib cage roll',
	'right turn',
	'shadow position',
	'shoulder isolation',
	'side basic',
	'side dip',
	'slide',
	'slow motion',
	'snake',
	'spiral turn',
	'stomp',
	'sweetheart',
	'syncopation',
	'tap step',
	'toe tap',
	'transition',
	'triple step',
	'trust fall',
	'wrap and unwrap',
];

export const salsaMoves: string[] = [
	'accent',
	'aerial',
	'arm styling',
	'back spot turn',
	'basic step',
	'break',
	'check turn',
	'closed position',
	'copa',
	'cross body lead',
	'cuban motion',
	'cuban shuffle',
	'dile que no',
	'dip',
	'double turn',
	'enchufla',
	'entrance',
	'exit',
	'exhibela',
	'flare',
	'flow',
	'footwork',
	'free spin',
	'guapea',
	'hair comb',
	'hammerlock',
	'hand styling',
	'hand toss',
	'hook turn',
	'inside turn',
	'isolation',
	'kick',
	'left turn',
	'lift',
	'mambo step',
	'open break',
	'open position',
	'outside turn',
	'pa arriba',
	'paseo',
	'pivot turn',
	'right turn',
	'rueda de casino',
	'setenta',
	'shadow position',
	'shines',
	'shoulder check',
	'side step',
	'slide',
	'sombrero',
	'stomp',
	'suzie q',
	'sweetheart',
	'syncopation',
	'tap step',
	'transition',
	'triple turn',
	'vacilala',
	'wrap and unwrap',
];

export function getMovesForDance(dance: string): string[] {
	switch (dance) {
		case 'bachata': return bachataMoves;
		case 'salsa': return salsaMoves;
		default: return [...new Set([...bachataMoves, ...salsaMoves])].sort();
	}
}
